name: bus2_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  get: ^4.7.3
  hive: ^2.2.3
  http: ^1.6.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
